namespace StarTrekAdventures.Helpers;

public static class PastimeGenerator
{
    public static string GeneratePastime()
    {
        return Pastimes.OrderBy(n => Util.GetRandom()).First();
    }

    private static readonly List<string> Pastimes = new()
    {
        "3D Chess",
        "20th Century Earth Cinema",
        "20th Century North American Culture",
        "Acting",
        "Ancient Earth Literature",
        "Andorian Blues",
        "Andorian Expressionist Painters",
        "Archaic Weapons",
        "Art",
        "Ballet",
        "Baseball",
        "Boxing",
        "Camping",
        "Cardassian Enigma Tales",
        "Carpentry",
        "Chess",
        "Chula",
        "Clarinet",
        "Climbing",
        "Cooking",
        "Crime Novels",
        "Dabo",
        "Dancing",
        "Directing",
        "Distance Running",
        "Earth History",
        "Exploring Other Cultures",
        "Fashion Design",
        "History",
        "Holo-programming",
        "Holography",
        "Holonovels",
        "Horseback Riding",
        "Ice Hockey",
        "Jazz Music",
        "Kadis-kot",
        "Kal-toh",
        "Kayaking",
        "Klingon opera",
        "Meditation",
        "Opera",
        "Outdoor Recreation",
        "Painting",
        "Parrises Squares",
        "Photography",
        "Poker",
        "Physical Fitness",
        "Reading",
        "Rock-Climbing and Spelunking",
        "Russian History",
        "Sculpture",
        "Shakespeare",
        "Singing",
        "Skydiving",
        "Social Drinking",
        "Soccer",
        "Springball",
        "Swimming",
        "Tailoring",
        "Tennis",
        "Theater",
        "Tongo",
        "Track & Field",
        "Trombone",
        "Vulcan Lute",
        "Vulcan Poetry",
        "Water Polo",
        "Wilderness Survival",
        "Writing Fiction",
    };
}
